<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Yeastar-PC" name="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber" tests="50" failures="4" timestamp="8 May 2018 18:53:03 GMT" time="1998.645" errors="2">
  <testcase name="B4_makeCall2" time="56.290" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="E4_checkPhyAndVoip" time="95.124" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="D1_addEmergency_line" time="102.227" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="G6_deleteAll_no" time="9.946" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_eventCenter7" time="10.354" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="G2_deleteOne_no" time="8.138" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber">
    <error type="org.openqa.selenium.WebDriverException" message="unknown error: Cannot read property &#039;id&#039; of undefined
  (Session info: chrome=66.0.3359.117)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 42 milliseconds
Build info: version: &#039;2.53.1&#039;, revision: &#039;a36b8b1cd5757287168e54b817830adce9b0158d&#039;, time: &#039;2016-06-30 19:26:09&#039;
System info: host: &#039;Yeastar-PC&#039;, ip: &#039;192.168.11.194&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;x86&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_121&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7), userDataDir=C:\Users\Yeastar\AppData\Local\Temp\scoped_dir10444_5548}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=66.0.3359.117, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=false, acceptInsecureCerts=false, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: 76eb902983fbed9b6c1e1045807ff90e">
      <![CDATA[org.openqa.selenium.WebDriverException: unknown error: Cannot read property 'id' of undefined
  (Session info: chrome=66.0.3359.117)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 42 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'Yeastar-PC', ip: '192.168.11.194', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7), userDataDir=C:\Users\Yeastar\AppData\Local\Temp\scoped_dir10444_5548}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=66.0.3359.117, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=false, acceptInsecureCerts=false, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: 76eb902983fbed9b6c1e1045807ff90e
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
	at com.yeastar.swebtest.driver.SwebDriver.executeJs(SwebDriver.java:668)
	at com.yeastar.swebtest.driver.SwebDriver.gridClick(SwebDriver.java:165)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber.G2_deleteOne_no(EmergencyNumber.java:1041)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- G2_deleteOne_no -->
  <testcase name="E1_voipAndPhysical" time="44.941" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_EventCenter3" time="13.020" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber">
    <failure type="java.lang.AssertionError" message="EventName查看">
      <![CDATA[java.lang.AssertionError: EventName查看
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1086)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertInclude(YsAssert.java:1225)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber.F2_EventCenter3(EmergencyNumber.java:863)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- F2_EventCenter3 -->
  <testcase name="D4_check_spx" time="57.106" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_EventCenter1" time="10.298" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C1_edittrunk_Unavail" time="34.905" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="B4_makeCall1" time="11.094" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C8_checkNotification" time="55.721" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F1_Contacts1" time="28.158" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_EventCenter5" time="45.405" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber">
    <failure type="java.lang.AssertionError" message="CDR呼叫方检测 【预期：1101dial111 [Emergency] 实际：Warning】">
      <![CDATA[java.lang.AssertionError: CDR呼叫方检测 【预期：1101dial111 [Emergency] 实际：Warning】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1086)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:579)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:142)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:116)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:199)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:262)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber.F2_EventCenter5(EmergencyNumber.java:900)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- F2_EventCenter5 -->
  <testcase name="F2_EventCenter4" time="8.176" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F1_Contacts2" time="46.356" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber">
    <failure type="java.lang.AssertionError" message="CDR呼叫方检测 【预期：Warning 实际：1000dial111 [Emergency]】">
      <![CDATA[java.lang.AssertionError: CDR呼叫方检测 【预期：Warning 实际：1000dial111 [Emergency]】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1086)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:579)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:142)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:116)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:199)
	at com.yeastar.swebtest.driver.YSMethod.YS_Extension.checkCDR(YS_Extension.java:262)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber.F1_Contacts2(EmergencyNumber.java:769)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- F1_Contacts2 -->
  <testcase name="A1_registerExtensions" time="50.018" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C4_checkTrunk1" time="62.184" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="H_recovery" time="47.873" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="G5_deletePart_yes" time="13.518" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="B2_makeCall" time="64.169" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C6_checkTrunk" time="82.782" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_eventCenter6" time="10.940" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber">
    <error type="org.openqa.selenium.WebDriverException" message="unknown error: Cannot read property &#039;id&#039; of undefined
  (Session info: chrome=66.0.3359.117)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 61 milliseconds
Build info: version: &#039;2.53.1&#039;, revision: &#039;a36b8b1cd5757287168e54b817830adce9b0158d&#039;, time: &#039;2016-06-30 19:26:09&#039;
System info: host: &#039;Yeastar-PC&#039;, ip: &#039;192.168.11.194&#039;, os.name: &#039;Windows 7&#039;, os.arch: &#039;x86&#039;, os.version: &#039;6.1&#039;, java.version: &#039;1.8.0_121&#039;
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7), userDataDir=C:\Users\Yeastar\AppData\Local\Temp\scoped_dir10444_5548}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=66.0.3359.117, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=false, acceptInsecureCerts=false, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: 76eb902983fbed9b6c1e1045807ff90e">
      <![CDATA[org.openqa.selenium.WebDriverException: unknown error: Cannot read property 'id' of undefined
  (Session info: chrome=66.0.3359.117)
  (Driver info: chromedriver=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7),platform=Windows NT 6.1.7601 SP1 x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 61 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'Yeastar-PC', ip: '192.168.11.194', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_121'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, mobileEmulationEnabled=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.37.544315 (730aa6a5fdba159ac9f4c1e8cbc59bf1b5ce12b7), userDataDir=C:\Users\Yeastar\AppData\Local\Temp\scoped_dir10444_5548}, takesHeapSnapshot=true, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, hasTouchScreen=false, version=66.0.3359.117, platform=XP, browserConnectionEnabled=false, nativeEvents=true, acceptSslCerts=false, acceptInsecureCerts=false, locationContextEnabled=true, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, cssSelectorsEnabled=true, setWindowRect=true, unexpectedAlertBehaviour=}]
Session ID: 76eb902983fbed9b6c1e1045807ff90e
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at org.openqa.selenium.remote.RemoteWebDriver.executeScript(RemoteWebDriver.java:577)
	at com.yeastar.swebtest.driver.SwebDriver.executeJs(SwebDriver.java:668)
	at com.yeastar.swebtest.driver.SwebDriver.gridContent(SwebDriver.java:234)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber.F2_eventCenter6(EmergencyNumber.java:910)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- F2_eventCenter6 -->
  <testcase name="G4_deletePart_no" time="18.537" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C2_checkUnavailTrunk" time="33.707" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="D3_check_iax" time="56.980" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C5_deleteTrunk_addNotification" time="31.850" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="D5_check_pstn" time="58.494" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="E2_checkVoipAndPhy" time="55.988" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="E6_checkPhyAndPhy" time="95.879" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C4_checkTrunk2" time="91.103" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C3_addTrunk" time="47.346" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="G1_addNumber" time="4.312" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="E5_PhyAndPhy" time="36.287" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="D5_check_bri" time="64.317" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="D6_check_e1" time="0.032" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="B1_addEmergencyNum" time="41.391" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="B3_editEmergencyNumb" time="34.723" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_eventCenter9" time="25.022" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="G7_delteAll_yes" time="15.767" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="E3_PhyAndVoip" time="35.956" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="D7_check_gsm" time="0.028" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="A2_addUnavailTrunk" time="24.075" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_EventCenter2" time="88.127" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F3_recoveryEvent" time="20.277" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F2_eventCenter8" time="73.799" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="C7_deleteNotification" time="26.964" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="G3_deleteOne_yes" time="25.013" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber"/>
  <testcase name="F1_Contacts3" time="23.928" classname="com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber">
    <failure type="java.lang.AssertionError" message="EventTime查看">
      <![CDATA[java.lang.AssertionError: EventTime查看
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1086)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertInclude(YsAssert.java:1225)
	at com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber.F1_Contacts3(EmergencyNumber.java:798)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- F1_Contacts3 -->
</testsuite> <!-- com.yeastar.swebtest.testcase.DetailCase.pbxcase.EmergencyNumber -->
