<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Yeastar-PC" name="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter" tests="7" failures="1" timestamp="31 Aug 2017 11:30:59 GMT" time="107.661" errors="0">
  <testcase name="C_Answer" time="24.415" classname="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter">
    <failure type="java.lang.AssertionError" message="分机1100接听 【预期：true 实际：false】">
      <![CDATA[java.lang.AssertionError: 分机1100接听 【预期：true 实际：false】
	at com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1086)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:579)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:142)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:116)
	at com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:333)
	at com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter.C_Answer(EventCenter.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </failure>
  </testcase> <!-- C_Answer -->
  <testcase name="B_EventSettings" time="6.331" classname="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter"/>
  <testcase name="E_DeleteNotification" time="8.360" classname="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter"/>
  <testcase name="G_CheckLog" time="13.078" classname="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter"/>
  <testcase name="F_CheckLog" time="24.157" classname="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter"/>
  <testcase name="D_CheckEventLog" time="12.937" classname="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter"/>
  <testcase name="A_AddContact" time="18.383" classname="com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter"/>
</testsuite> <!-- com.yeastar.swebtest.testcase.smokecase.syscase.EventCenter -->
