<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="pbxcore"
           tests="10"
           failures="3"
           errors="0"
           skipped="0"
           time="468.834">
  <properties />
            <testcase name="D2_CalltoDISA1" time="54.980" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcase.Disa_PinList">
                <failure type="java.lang.AssertionError"
                  message="预期3002会Talking 【预期：3 实际：-1】"
              >
<![CDATA[java.lang.AssertionError: 预期3002会Talking 【预期：3 实际：-1】
  com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
  com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
  com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
  com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
  com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:429)
  com.yeastar.swebtest.driver.SwebDriver.ysAssertWithHangup(SwebDriver.java:912)
  com.yeastar.swebtest.testcase.RegressionCase.pbxcase.Disa_PinList.D2_CalltoDISA1(Disa_PinList.java:167)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:774)
  org.testng.TestRunner.run(TestRunner.java:624)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
  org.testng.SuiteRunner.run(SuiteRunner.java:261)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
  org.testng.TestNG.run(TestNG.java:1048)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
  org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
      </failure>

          </testcase>
            <testcase name="E_Disa1" time="72.415" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcase.Disa_PinList">
                <failure type="java.lang.AssertionError"
                  message="外线呼出进入pin1List 【预期：true 实际：false】"
              >
<![CDATA[java.lang.AssertionError: 外线呼出进入pin1List 【预期：true 实际：false】
  com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
  com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
  com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
  com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
  com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:337)
  com.yeastar.swebtest.testcase.RegressionCase.pbxcase.Disa_PinList.E_Disa1(Disa_PinList.java:180)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:774)
  org.testng.TestRunner.run(TestRunner.java:624)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
  org.testng.SuiteRunner.run(SuiteRunner.java:261)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
  org.testng.TestNG.run(TestNG.java:1048)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
  org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
      </failure>

          </testcase>
            <testcase name="C1_CalltoDISA1" time="50.547" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcase.Disa_PinList">
                <failure type="java.lang.AssertionError"
                  message="预期3001会Talking 【预期：3 实际：-1】"
              >
<![CDATA[java.lang.AssertionError: 预期3001会Talking 【预期：3 实际：-1】
  com.yeastar.swebtest.tools.ysassert.YsAssert.fail(YsAssert.java:1092)
  com.yeastar.swebtest.tools.ysassert.YsAssert.failNotEquals(YsAssert.java:583)
  com.yeastar.swebtest.tools.ysassert.YsAssert.assertEqualsImpl(YsAssert.java:146)
  com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:120)
  com.yeastar.swebtest.tools.ysassert.YsAssert.assertEquals(YsAssert.java:429)
  com.yeastar.swebtest.driver.SwebDriver.ysAssertWithHangup(SwebDriver.java:912)
  com.yeastar.swebtest.testcase.RegressionCase.pbxcase.Disa_PinList.C1_CalltoDISA1(Disa_PinList.java:124)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
  org.testng.TestRunner.privateRun(TestRunner.java:774)
  org.testng.TestRunner.run(TestRunner.java:624)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
  org.testng.SuiteRunner.run(SuiteRunner.java:261)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
  org.testng.TestNG.run(TestNG.java:1048)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:293)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:91)
  org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="D1_EditDisa" time="40.147" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcase.Disa_PinList" />
                <testcase name="G_Delete" time="107.042" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcase.Disa_PinList" />
                <testcase name="G_Recovery" time="35.145" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcase.Disa_PinList" />
                <testcase name="B2_EditInroute" time="38.835" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcase.Disa_PinList" />
                <testcase name="B1_CreateDisa" time="36.249" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcase.Disa_PinList" />
                <testcase name="A0_register" time="16.567" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcase.Disa_PinList" />
                <testcase name="A1_CreatePin" time="16.907" classname="com.yeastar.swebtest.testcase.RegressionCase.pbxcase.Disa_PinList" />
      
</testsuite>
